### ISSUE TITLE
Set up semantic release for Chrome

### ISSUE THREAD

**Issue by wkillerud** [podium-lib/dev-tool#72]
- [x] Get access to the Chrome Web Store account that [publishes the extension](https://chromewebstore.google.com/detail/podium-development-extens/jdlcejoeifgnnnckhnhapbmgieajaipl) (@digitalsadhu is on the case 🕵️ )
- [x] Get the three required environment secrets: https://github.com/GabeDuarteM/semantic-release-chrome/blob/master/Authentication.md
- [x] Configure https://github.com/GabeDuarteM/semantic-release-chrome
- [x] Test the automated release pipeline

**Comment by digitalsadhu** [comment]
No response from Google re: transferring the extension in what? A week or so? Don't remember even getting a confirmation email or anything.
